# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  setup:
    cmds:
      - go mod tidy
    desc: Setup project dependencies

  lint:
    cmds:
      - go vet
      - go fmt
    desc: Run linters

  test:
    cmds:
      - go test
    desc: Run tests

  run:
    cmds:
      - go run main.go {{.CLI_ARGS}}
    desc: Run application

  build:
    env:
      GOOS: "{{.OS}}"
      GOARCH: "{{.ARCH}}"
    cmds:
      - go build -o dist/ralph-{{.OS}}-{{.ARCH}}{{.EXT}}
    requires:
      vars:
        - OS
        - ARCH
    desc: Build binary for a single OS

  build-all:
    cmds:
      - task build OS=windows ARCH=amd64 EXT=.exe
      - task build OS=darwin ARCH=amd64 EXT=
      - task build OS=linux ARCH=amd64 EXT=
    desc: Build binaries for Windows, macOS and Linux
